id: PCA9DB392
initial_creation_type: ocr
source_metadata:
  volumes:
    f6952faf154f4dc29b71d02dfff9d39a:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
